# Results will be saved in root_dir/Model_outputs/output_dir/
output_dir: 'debugger'

Nb_GRBs: '1e5'

# Samples can be anything you define in the samples.yml file
samples: ['Stern', 'EpGBM', 'eBAT6', 'Swift', 'ECLAIRs', 'SHOALS', 'GBM_sample', 'BATSE_5B_sample']

# Constraints can by anything you define in the obs_constraints.yml file
constraints: ['Stern', 'EpGBM', 'eBAT6']
